### ISSUE TITLE
Make shield.io badge text less verbose

### ISSUE THREAD

**Issue by James-Osgood** [arrai-innovations/circleci-orbs#1]
Currently, all badges include the branch name. Some include the Python version. This makes it difficult to arrange on a project's readme.

We could find the following, reduced badge text more useful for the following services:
* CircleCI: `TESTS`
* Python/JS coverage: `COVERAGE`
* Flake8: `FLAKE8`
* ESLint: `ESLINT`

**Comment by pmack** [comment]
For coverage badges the text is now hard-coded to 'coverage'. The generic status badge generator is now sensitive to a 'label' parameter, which defaults to the job name. Waiting for CircleCI to come back to life so the new orb can be published.

**Comment by pmack** [comment]
This has been published and available as of [arrai/utils@1.3.0](https://circleci.com/orbs/registry/orb/arrai/utils).

**Comment by pmack** [comment]
The following orbs have been updated accordingly.

- [arrai/badass@2.8.0](https://circleci.com/orbs/registry/orb/arrai/badass)
- [arrai/flake8@4.6.0](https://circleci.com/orbs/registry/orb/arrai/flake8)
- [arrai/eslint@1.2.0](https://circleci.com/orbs/registry/orb/arrai/eslint)
