### ISSUE TITLE
ignore rsync related steps when missing DOCS_HOST env var

### ISSUE THREAD

**Issue by jhillacre** [arrai-innovations/circleci-orbs#3]
It would be nice if we could have tests run on pull requests from forks. Circleci has a setting to not pass secrets to these instances. The rsync steps in utils would blow up without proper ssh keys / environment vars. We should:

* make all the steps in the utils orbs skip if `DOCS_HOST` is not set in the environment. this skip should not be considered a failure.
* bump the utils version in the other orbs (particularly, flake8).
* bump the utils/flake8 orbs in public repos' config.yml.

**Comment by pmack** [comment]
This is available as of [utils orb 1.4.0](https://circleci.com/orbs/registry/orb/arrai/utils?version=1.4.0).
